### ISSUE TITLE
INSTALL????

### ISSUE THREAD

**Issue by gitfu** [cisco/ciscohls#2]
When are the build and install instructions?

**Comment by snoby** [comment]
Hi,
They are both autotools based projects.  Therefore:

cd libhls
autoreconf -ivf
./configure
make
make install

cd..
cd gsthls
autoreconf -ivf
./configure
make
make install

**Comment by gitfu** [comment]
I always forget to add the '-ivf' to autoreconf. 

Thank you for the quick reply.
